### ISSUE TITLE
CVPR 2024 workshop papers not added

### ISSUE THREAD

**Issue by Nawrin14** [youngfish42/Awesome-FL#35]
Hi, I noticed that the CVPR 2022 and 2023 workshop papers have been added, but not the CVPR 2024 workshop papers. Can you please add them as well? Thanks.

**Comment by youngfish42** [comment]
Thank you for your interest in this repository.

I checked the website of the [CVPR 2024 workshop](https://openreview.net/group?id=thecvf.com/CVPR/2024/Workshop) and visited the list of accepted papers for all workshops, but did not find any articles related to federated learning.

If you have better suggestions, please point them out. You are also welcome to add papers directly to this repository as contributions, thank you!

**Comment by Nawrin14** [comment]
Thanks for your response. I was referring to this workshop https://openaccess.thecvf.com/CVPR2024_workshops/FedVision-2024

**Comment by youngfish42** [comment]
Thank you for your suggestion, the corresponding paper has now been added to the list.
